server:
  port: 8090

spring:
  application:
    name: ms-exchange-rate
  datasource:
    url: jdbc:h2:mem:db_test
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    defer-datasource-initialization: true